_clients/REST/RazorPages/Pages/Accounts/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using RazorPages.CoreServices;

namespace RazorPages.Pages.Accounts
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public CreateAccountServiceModel NewAccount {get; set;}

        [BindProperty]
        public CreateAccountCommandResponse CreateAccountResponse { get; set; }

        private string baseUrl { get; set; }

        public CreateModel(IConfiguration configuration)
        {
            baseUrl = configuration.GetSection("CoreServices").GetSection("BaseUrl").Value;
        }

        public void OnGet()
        {
            CreateAccountResponse = null;
            NewAccount = new CreateAccountServiceModel();
        }

        public async Task<IActionResult> OnPost()
        {
            var client = new AccountsClient(baseUrl);
            CreateAccountResponse = await client.CreateAsync(NewAccount);


            // Using HttpClient without OpenAPI/Swagger:
            //HttpClient client = new HttpClient();
            //HttpResponseMessage response = await client.PostAsJsonAsync(
            //baseUrl + "/api/accounts", NewAccount);


            if (!CreateAccountResponse.IsSuccess.Value)
            {
                return Page();
            }
            else
            {
                return RedirectToPage("Index");
            }       
        }

        public async Task<IActionResult> OnPostClear()
        {
            //ValidationIssues = null;
            //NewAccount = null;

            return RedirectToPage("Create");
            //return Page();
        }
    }
}

_clients/REST/RazorPages/Pages/Accounts/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using RazorPages.CoreServices;

namespace RazorPages.Pages.Accounts
{
    public class DetailsModel : PageModel
    {
        [BindProperty]
        public AccountDetailsViewModel AccountDetails { get; set; }

        [BindProperty]
        public string Error { get; set; }

        [BindProperty]
        public string Message { get; set; }

        private string NameKey { get; set; }

        private string baseUrl { get; set; }

        public DetailsModel(IConfiguration configuration)
        {
            baseUrl = configuration.GetSection("CoreServices").GetSection("BaseUrl").Value;
        }

        public async Task<IActionResult> OnGet(string nameKey)
        {
            NameKey = nameKey;

            var client = new AccountsClient(baseUrl);
            AccountDetails = await client.DetailsAsync(NameKey);

            return Page();
        }

        public async Task<IActionResult> OnPostDelete(string id)
        {
            try
            {
                var client = new AccountsClient(baseUrl);
                var results = await client.DeleteAsync(id);

                if (results.IsSuccess.Value == true)
                {
                    Message = "Account closed";
                    return Page();
                    //return RedirectToPage("Index");
                }
                else
                {
                    Error = results.Message;
                    return Page();
                }
            }
            catch(Exception ex)
            {
                Error = $"An error occured: { ex.Message }";
                return Page();
            }
        }
    }
}

_clients/REST/RazorPages/Pages/Accounts/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using RazorPages.CoreServices;

namespace RazorPages.Pages.Accounts
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public AccountListResultsViewModel AccountListView { get; set; }

        private string baseUrl { get; set; }

        public IndexModel(IConfiguration configuration)
        {
            baseUrl = configuration.GetSection("CoreServices").GetSection("BaseUrl").Value;
            AccountListView = new AccountListResultsViewModel();
        }

        public async Task<IActionResult> OnGet()
        {
            var client = new AccountsClient(baseUrl);
            var response = await client.ListAsync(10, OrderBy.CreatedDate, OrderDirection.DESC, "");

            if(response != null)
            {
                AccountListView = response;
            }
            else
            {
                AccountListView.Count = 0;
            }

            return Page();

        }

        public async Task<IActionResult> OnGetNext()
        {
            var client = new AccountsClient(baseUrl);
            var response = await client.ListAsync(10, OrderBy.CreatedDate, OrderDirection.DESC, AccountListView.ContinuationToken);


            AccountListView = response;

            return Page();

        }
    }
}

_clients/REST/RazorPages/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPages.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

_clients/REST/RazorPages/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPages.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

_clients/REST/RazorPages/Pages/Accounts/Create.cshtml
@page
@model RazorPages.Pages.Accounts.CreateModel
@{
    ViewData["Title"] = "Create";
}

@if (Model.CreateAccountResponse == null)
{
    <h1>Create Account</h1>

    <form method="post">

        <div class="form-group">
            <label>Account Name:</label>
            <input class="form form-control" type="text" asp-for="@Model.NewAccount.Name" />
        </div>

        <div class="form-group">
            <label>First Name:</label>
            <input class="form form-control" type="text" asp-for="@Model.NewAccount.FirstName" />
        </div>

        <div class="form-group">
            <label>Last Name:</label>
            <input class="form form-control" type="text" asp-for="@Model.NewAccount.LastName" />
        </div>

        <div class="form-group">
            <label>Email:</label>
            <input class="form form-control" type="text" asp-for="@Model.NewAccount.Email" />
        </div>

        <hr />

        <a href="/Accounts" class="btn btn-success">Cancel</a>
        <button asp-page-handler="Post" class="btn btn-primary">Submit</button>
        <button asp-page-handler="Clear" class="btn btn-default">Clear</button>

    </form>
}
else
{
    if (Model.CreateAccountResponse.IsSuccess == false)
    {
        <div class="alert alert-danger">
            @Model.CreateAccountResponse.Message
        </div>

        <form method="post">

            @if (Model.CreateAccountResponse.ValidationIssues.Count > 0)
            {

            <div class="form-group">

                @if (Model.CreateAccountResponse.ValidationIssues.FirstOrDefault(v => v.PropertyName == "Name") != null)
                {
                    <b class="text-danger">Account Name:</b><br />
                    foreach (var validationIssue in Model.CreateAccountResponse.ValidationIssues.First(v => v.PropertyName == "Name").PropertyFailures)
                    {                       
                        <small class="text-danger">@validationIssue</small>
                    }
                    <input class="form form-control border-danger" type="text" asp-for="@Model.NewAccount.Name" />
                }
                else
                {
                    <label>Account Name:</label>
                    <input class="form form-control" type="text" asp-for="@Model.NewAccount.Name" />
                }
            </div>


                <div class="form-group">


                    @if (Model.CreateAccountResponse.ValidationIssues.FirstOrDefault(v => v.PropertyName == "FirstName") != null)
                    {
                        <b class="text-danger">First Name:</b><br />
                        foreach (var validationIssue in Model.CreateAccountResponse.ValidationIssues.First(v => v.PropertyName == "FirstName").PropertyFailures)
                        {

                            <small class="text-danger">@validationIssue</small>
                        }
                        <input class="form form-control border-danger" type="text" asp-for="@Model.NewAccount.FirstName" />
                    }
                    else
                    {
                        <label>First Name:</label>
                        <input class="form form-control" type="text" asp-for="@Model.NewAccount.FirstName" />
                    }
                </div>


                <div class="form-group">
                    @if (Model.CreateAccountResponse.ValidationIssues.FirstOrDefault(v => v.PropertyName == "LastName") != null)
                    {
                        <b class="text-danger">Last Name:</b><br />
                        foreach (var validationIssue in Model.CreateAccountResponse.ValidationIssues.First(v => v.PropertyName == "LastName").PropertyFailures)
                        {
                            <small class="text-danger">@validationIssue</small>
                        }
                        <input class="form form-control border-danger" type="text" asp-for="@Model.NewAccount.LastName" />
                    }
                    else
                    {
                        <label>Last Name:</label>
                        <input class="form form-control" type="text" asp-for="@Model.NewAccount.LastName" />
                    }
                </div>


                <div class="form-group">
                    @if (Model.CreateAccountResponse.ValidationIssues.FirstOrDefault(v => v.PropertyName == "Email") != null)
                    {
                        <b class="text-danger">Email:</b><br />
                        foreach (var validationIssue in Model.CreateAccountResponse.ValidationIssues.First(v => v.PropertyName == "Email").PropertyFailures)
                        {
                            <small class="text-danger">@validationIssue</small>
                        }
                            <input class="form form-control border-danger" type="text" asp-for="@Model.NewAccount.Email" />
                        }
                        else
                        {
                            <label>Email:</label>
                            <input class="form form-control" type="text" asp-for="@Model.NewAccount.Email" />
                        }
                </div>

            }

            <hr />

            <a href="/Accounts" class="btn btn-success">Cancel</a>
            <button asp-page-handler="Post" class="btn btn-primary">Submit</button>
            <button asp-page-handler="Clear" class="btn btn-default">Clear</button>

        </form>
        
    }
    else if (Model.CreateAccountResponse.IsSuccess == true)
    {
        <div class="alert alert-success">
            Account created!
        </div>

        <a href="/Accounts" class="btn btn-primary">Back to list</a>
        <a href="/Create" class="btn btn-success">Create another</a>
    }
}

_clients/REST/RazorPages/Pages/Accounts/Details.cshtml
@page "{nameKey}"
@model RazorPages.Pages.Accounts.DetailsModel
@{
    ViewData["Title"] = "Details";
}

@if (!String.IsNullOrEmpty(Model.Error))
{
    <div class="alert alert-danger">@Model.Error</div>
}
else if (!String.IsNullOrEmpty(Model.Message))
{
    <div class="alert alert-success">@Model.Message</div>
    <a class="btn btn-primary" asp-page="Index">OK</a>
}
else
{
    <h1>@Model.AccountDetails.Account.Name</h1>
    <h3>@Model.AccountDetails.Account.NameKey</h3>
    <small>@Model.AccountDetails.Account.Id</small>

    <hr />

    <form asp-page="Details" method="post" typeof="@Model.AccountDetails">


        @if (Model.AccountDetails.DeleteEnabled.Value)
        {
            <button class="btn btn-danger" asp-page-handler="Delete" asp-route-id="@Model.AccountDetails.Account.Id">Close account</button>
        }

    </form>

}

_clients/REST/RazorPages/Pages/Accounts/Index.cshtml
@page
@model RazorPages.Pages.Accounts.IndexModel
@{
    ViewData["Title"] = "Index";
}

<h1>Accounts</h1>

@if (Model.AccountListView.Count == 0)
{
    <p>No accounts yet.</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Account Name</th>
                <th scope="col">Created</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var account in Model.AccountListView.Accounts)
            {
            <tr>
                <th scope="row">@account.Name</th>
                <td>@account.CreatedDate.Value.ToLocalTime().ToString("MM/dd/yyyy hh:mm tt")</td>
                <td style="text-align:right">
                    <a class="btn btn-sm btn-outline-primary" asp-page="details" asp-route-nameKey="@account.NameKey">Details</a>
                </td>

            </tr>
            }
        </tbody>
    </table>
}

<hr />

<a class="btn btn-primary" asp-page="Create">Create Account</a>

_clients/REST/RazorPages/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-left">
    <h1 class="display-4">Razor Pages Client</h1>
    <h4>About</h4>
    <p>This project serves as an example for integrating with Core Services. The "CoreServices" folder is where our NSwag generated client code and configuration are placed.</p>
    
    <h4>Using API Client</h4>
    <p>Set the baseUrl property in the Client constructor of the generated CoreServices class:</p>
    <p class="alert">

    </p>

    <h4>Configuration</h4>
    <p>To use the correct services endpoint update the settings here:</p>

    <h4>NSwag</h4>
</div>

_clients/REST/RazorPages/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorPages</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorPages</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Accounts/Index">Accounts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - RazorPages - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>